boot.o: boot.S multiboot.h x86_desc.h types.h
enablePaging.o: enablePaging.S
wrappers.o: wrappers.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h types.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h keyboard.h filesys.h
keyboard.o: keyboard.c keyboard.h lib.h types.h i8259.h
lib.o: lib.c lib.h types.h keyboard.h
paging.o: paging.c paging.h x86_desc.h types.h lib.h
rtc.o: rtc.c lib.h types.h i8259.h rtc.h
terminal.o: terminal.c keyboard.h lib.h types.h terminal.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h terminal.h keyboard.h \
  rtc.h filesys.h
